import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "id" | "en" | "th" | "zh" | "ja" | "km" | "tl" | "ko";

export const translations: Record<Language, Record<string, string>> = {
  id: {
    "sign_in": "MASUK",
    "sign_up": "DAFTAR",
    "home": "Beranda",
    "wallet": "Dompet",
    "hub_kami": "Hub Kami",
    "promotion": "Promosi",
    "p2p": "P2P",
    "language": "Bahasa",
    "deposit": "Deposit",
    "withdraw": "Penarikan",
    "game_hit": "Game Hit",
    "slot": "Slot",
    "casino": "Casino",
    "sportsbook": "Sportsbook",
    "fishing": "Fishing",
    "arcade": "Arcade",
    "cockfighting": "Sabung Ayam",
    "togel": "Togel",
    "play": "MAINKAN",
    "profile": "Profil",
    "history": "Riwayat",
    "cashback": "Cashback",
    "earn_money": "Hasilkan Uang",
    "credit_point": "Kredit/Poin Gratis",
    "coupon": "Kupon",
    "randombox": "Randombox",
    "wheel": "Roda Keberuntungan",
    "check_in": "Check In",
    "ranking": "Peringkat",
    "contact_us": "Hubungi Kami",
    "switch_language": "Ubah Bahasa",
    "manual": "Panduan",
    "download_guild": "Unduh Guild",
    "announcement": "🎉 Pengumuman: DEMO Gacor Gaming Dapatkan Bonus & Promosi Spesial Hari Ini",
    "free_spins": "💰 Menang Besar dengan 100 Putaran Gratis - Deposit Hanya $100",
    "promotion_bonus": "🎁 Promosi Spesial: Bonus 50% untuk Semua Game Setiap Hari",
    "welcome_bonus": "⭐ Bergabunglah Sekarang dan Dapatkan 100 Poin Gratis sebagai Bonus Selamat Datang",
    "search_games": "Cari game...",
    "username": "Nama Pengguna",
    "password": "Kata Sandi",
    "confirm_password": "Konfirmasi Kata Sandi",
    "email": "Email",
    "phone": "Nomor Telepon",
    "login": "Masuk",
    "register": "Daftar",
    "forgot_password": "Lupa Kata Sandi",
    "logout": "Keluar",
    "have_account": "Sudah memiliki akun?",
    "password_mismatch": "Kata sandi tidak cocok",
    "phone_number": "Nomor Telepon",
    "please_enter_phone": "Silakan, masukkan nomor telepon Anda",
    "please_enter_password": "Silakan, masukkan kata sandi Anda",
    "remember_me": "Ingat saya",
    "forgot_password_q": "Lupa Kata Sandi??",
    "found_problem": "Menemukan masalah",
    "contact_customer_service": "Hubungi Layanan Pelanggan",
    "play": "MAINKAN",
    "credit_balance": "Saldo Kredit",
    "wallet": "Dompet",
    "promotion": "Promosi",
    "turnover": "Turnover",
    "credit_free": "Kredit Gratis",
    "point_free": "Poin Gratis",
    "coupon": "Kupon",
    "random_box": "Kotak Acak",
    "wheel": "Roda Keberuntungan",
    "exchange": "Tukar",
    "tournament": "Turnamen",
    "deposit_withdraw": "Deposit - Penarikan",
    "deposit": "Deposit",
    "withdraw": "Penarikan",
    "deposit_auto": "Deposit otomatis",
    "deposit_decimal": "Desimal Deposit",
    "truemoney": "Truemoney",
    "deposit_confirm_slip": "Konfirmasi Slip Deposit",
    "true_gift": "Hadiah Asli",
    "deposit_confirm": "Konfirmasi Deposit",
    "line_bot_notification": "Notifikasi Bot Line",
    "normal_withdraw": "Penarikan Normal",
    "max_withdraw": "Max Penarikan",
    "withdraw_to_account": "Tarik uang Anda ke akun",
    "bio": "BIO",
    "have_questions_readmore": "Ada pertanyaan lagi? Baca lebih lanjut",
    "hub_kami": "Hub Kami",
    "contact_us": "Hubungi Kami",
    "live_chat_support": "Dukungan Obrolan Langsung",
    "available_24_7": "Tersedia 24/7",
    "email": "Email",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "Menu Utama",
    "income_menu": "Menu Pendapatan",
    "event_menu": "Menu Acara",
    "more_menu": "Menu Lainnya",
    "logout": "Keluar",
    "user_id": "ID Pengguna",
    "balance": "Saldo",
    "point": "Poin",
    "choose_your_bank": "Pilih bank Anda",
    "enter_bank_number": "Masukkan nomor bank Anda",
    "name_lastname": "nama - nama belakang",
    "how_do_know_us": "Bagaimana Anda mengenal kami dari?",
    "choose_receive_bonus": "Pilih untuk menerima bonus atau tidak",
    "receive": "Terima",
    "not_receive": "Tidak terima",
    "sign_up_modal": "DAFTAR",
    "enter_banknumber": "Masukkan nomor Bank",
    "personal_info": "Informasi Pribadi",
    "bank_info": "Informasi Akun Bank",
    "bank_type": "Jenis Bank",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "Nama Akun Bank",
    "account_number": "Nomor Rekening",
    "banking": "Perbankan",
    "choose_deposit_method": "Pilih Metode Deposit",
    "choose_payment_method": "Pilih metode pembayaran yang Anda inginkan",
    "qris": "QRIS",
    "bank_transfer": "Bank Transfer",
    "e_wallet": "E-Wallet",
    "pulsa": "Pulsa",
    "scan_qr_instant": "Scan QR code untuk deposit instan",
    "transfer_bank_for_deposit": "Transfer bank untuk deposit aman",
    "dana_ovo_gopay": "DANA, OVO, GoPay, dan lainnya",
    "deposit_via_pulsa": "Deposit via pulsa prabayar",
    "instant": "Instant",
    "30_60_seconds": "30 - 60 Detik",
    "select_qris_provider": "Pilih Jasa QRIS",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "Online",
    "deposit_amount": "Jumlah Deposit",
    "withdraw_amount": "Jumlah Penarikan",
    "enter_deposit_amount": "Masukkan jumlah deposit",
    "idr": "IDR",
    "minimum": "Minimum",
    "maximum": "Maksimum",
    "choose_promo": "Pilih Promo (Opsional)",
    "choose_promo_optional": "Pilih promo (opsional)",
    "payment_summary": "Ringkasan Pembayaran",
    "total_deposit": "Jumlah Deposit:",
    "promo_discount": "Jumlah Pembayaran:",
    "total": "Total:",
    "confirm_deposit": "Kirim Deposit",
    "rp_0": "Rp 0",
    "select_your_account": "Pilih Rekening Anda",
    "destination_account": "Rekening Tujuan",
    "select_destination": "Pilih rekening tujuan",
    "bank_account_info": "Informasi Rekening",
    "bank_name": "Nama Bank",
    "account_holder": "Nama Pemegang Rekening",
    "recipient_number": "Nomor Penerima",
    "upload_receipt": "Bukti Pembayaran (Opsional)",
    "click_upload_receipt": "Klik untuk upload bukti pembayaran",
    "additional_notes": "Keterangan (opsional)",
    "enter_notes": "No.Ref / Nama Pengirim",
    "select_wallet": "Pilih E-Wallet",
    "select_ewallet_number": "Pilih nomor e-wallet",
    "select_admin_number": "Pilih Nomor Admin",
    "recipient_phone": "Nomor SN / Nomor Penerima",
    "enter_recipient_phone": "Masukkan nomor SN",
    "withdrawal": "Penarikan",
    "withdrawal_history": "Riwayat Penarikan",
    "coming_soon": "Segera Hadir",
    "history_transaction": "Riwayat Transaksi",
    "history_transaction_span": "Lihat semua transaksi anda",
    "filter_transaction": "Filter Transaksi",
    "filter_transaction_span": "Pilih periode dan jenis transaksi untuk melihat riwayat",
    "start_date": "Tanggal Mulai",
    "finish_date": "Tanggal Akhir",
    "type_transaction": "Jenis Transaksi",
    "search_history": "Cari Riwayat",
    "history_result": "Hasil Pencarian",
    "find_transaction":"transaksi ditemukan",
    "profile_information": "Informasi Profil",
    "profile_settings": "Pengaturan Profil",
    "profile_information": "Informasi Profil",
    "account_details": "Detail Akun",
    "account_tier": "Tier Akun",
    "change_password": "Ubah Kata Sandi",
    "current_password": "Kata Sandi Saat Ini",
    "enter_current_password": "Masukkan kata sandi saat ini",
    "new_password": "Kata Sandi Baru",
    "enter_new_password": "Masukkan kata sandi baru",
    "update_password_instruction": "Perbarui kata sandi Anda",
    "banking_accounts": "Rekening Bank",
    "add_bank": "Tambah Bank",
    "active": "Aktif",
    "security": "Keamanan",
    "referral_program": "Program Referral",
    "earn_bonus_from_referrals": "Dapatkan bonus dari referral Anda",
    "referral_app_info": "Aplikasi program referral dengan form terstruktur",
    "first_name": "Nama Depan",
    "enter_first_name": "Masukkan nama depan",
    "enter_email": "Masukkan alamat email",
    "enter_phone_number": "Masukkan nomor telepon",
    "address": "Alamat",
    "enter_address": "Masukkan alamat lengkap",
    "bank_ewallet": "Bank/E-Wallet Anda",
    "choose_bank_ewallet": "Pilih Bank/E-Wallet Anda",
    "identity_file": "File Identitas (KTP/SIM/Passport)",
    "click_upload_identity": "Klik atau seret file identitas Anda di sini",
    "file_format_limit": "Format: JPG, PNG - Maksimal 10MB",
    "submit_application": "Kirim Aplikasi",
    "referral_tree": "Pohon Referral",
    "total_referral": "Total Referral",
    "no_referrals_yet": "Belum ada referral",
    "invite_people_to_join": "Ajak orang untuk bergabung dan dapatkan bonus",
    "referral_structure_display": "Struktur referral Anda akan ditampilkan di sini",
    "data_turnover": "Data Turnover",
    "view_performance": "Pantau performa bemain Anda dengan filter",
    "filter_data": "Filter Data",
    "start_date": "Tanggal Mulai",
    "end_date": "Tanggal Selesai",
    "category": "Kategori",
    "provider": "Provider",
    "all_categories": "Semua Kategori",
    "all_providers": "Semua Provider",
    "search_data": "Cari Data",
    "search_results": "Hasil Pencarian",
    "results": "hasil",
    "no_data_yet": "Belum ada data turnover",
    "adjust_filter_to_see_data": "Ubah filter atau tanggal untuk melihat data turnover Anda",
    "statistics": "Statistik",
    "cancel": "Batal",
    "confirm": "Simpan",
    "send_application": "Kirim Aplikasi",

  },
  en: {
    "sign_in": "SIGN IN",
    "sign_up": "SIGN UP",
    "home": "Home",
    "wallet": "Wallet",
    "hub_kami": "Hub Kami",
    "promotion": "Promotion",
    "p2p": "P2P",
    "language": "Language",
    "deposit": "Deposit",
    "withdraw": "Withdraw",
    "game_hit": "Game Hit",
    "slot": "Slot",
    "casino": "Casino",
    "sportsbook": "Sportsbook",
    "fishing": "Fishing",
    "arcade": "Arcade",
    "cockfighting": "Sabung Ayam",
    "togel": "Togel",
    "play": "PLAY",
    "profile": "Profile",
    "history": "History",
    "cashback": "Cashback",
    "earn_money": "Earn Money",
    "credit_point": "Credit/Point Free",
    "coupon": "Coupon",
    "randombox": "Randombox",
    "wheel": "Wheel",
    "check_in": "Check In",
    "ranking": "Ranking",
    "contact_us": "Contact us",
    "switch_language": "Switch language",
    "manual": "Manual",
    "download_guild": "Download Guild",
    "announcement": "🎉 Announcement: DEMO Gacor Gaming Get Special Bonuses & Promotions Today",
    "free_spins": "💰 Win Big with Free Spins 100 - Deposit Only $100",
    "promotion_bonus": "🎁 Special Promotion: 50% Bonus on All Games Daily",
    "welcome_bonus": "⭐ Join Now and Get 100 Free Points as Welcome Bonus",
    "search_games": "Search games...",
    "username": "Username",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "email": "Email",
    "phone": "Phone Number",
    "login": "Login",
    "register": "Register",
    "forgot_password": "Forgot Password",
    "logout": "Logout",
    "have_account": "Already have an account?",
    "password_mismatch": "Passwords do not match",
    "phone_number": "Phone Number",
    "please_enter_phone": "Please, enter your phone number",
    "please_enter_password": "Please, enter your password",
    "remember_me": "Remember me",
    "forgot_password_q": "Forgot Password??",
    "found_problem": "Found a problem",
    "contact_customer_service": "Contact Customer Service",
    "play": "PLAY!",
    "credit_balance": "Credit Balance",
    "wallet": "Wallet",
    "promotion": "Promotion",
    "turnover": "Turnover",
    "credit_free": "Credit Free",
    "point_free": "Point Free",
    "coupon": "Coupon",
    "random_box": "Random Box",
    "wheel": "Wheel",
    "exchange": "Exchange",
    "tournament": "Tournament",
    "deposit_withdraw": "Deposit - Withdraw",
    "deposit": "Deposit",
    "withdraw": "Withdraw",
    "deposit_auto": "Deposit auto",
    "deposit_decimal": "Deposit decimal",
    "truemoney": "Truemoney",
    "deposit_confirm_slip": "Deposit confirm slip",
    "true_gift": "True gift",
    "deposit_confirm": "Deposit confirm",
    "line_bot_notification": "Line bot notification",
    "normal_withdraw": "Normal withdraw",
    "max_withdraw": "Max Withdraw",
    "withdraw_to_account": "Withdraw you money to the account",
    "bio": "BIO",
    "have_questions_readmore": "Have any further questions? Readmore",
    "hub_kami": "Hub Kami",
    "contact_us": "Contact us",
    "live_chat_support": "Live Chat Support",
    "available_24_7": "Available 24/7",
    "email": "Email",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "Main Menu",
    "income_menu": "Income Menu",
    "event_menu": "Event Menu",
    "more_menu": "More Menu",
    "logout": "Logout",
    "user_id": "User ID",
    "balance": "Balance",
    "point": "Point",
    "choose_your_bank": "Choose your bank",
    "enter_bank_number": "Enter your Bank number",
    "name_lastname": "name - lastname",
    "how_do_know_us": "How do you know us from?",
    "choose_receive_bonus": "Choose to receive a bonus or not",
    "receive": "Receive",
    "not_receive": "Not receive",
    "sign_up_modal": "SIGN UP",
    "enter_banknumber": "Enter your Banknumber",
    "personal_info": "Personal Information",
    "bank_info": "Bank Account Information",
    "bank_type": "Bank Type",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "Bank Account Name",
    "account_number": "Account Number",
    "banking": "Banking",
    "choose_deposit_method": "Choose Deposit Method",
    "choose_payment_method": "Choose your preferred payment method",
    "qris": "QRIS",
    "bank_transfer": "Bank Transfer",
    "e_wallet": "E-Wallet",
    "pulsa": "Pulsa",
    "scan_qr_instant": "Scan QR code for instant deposit",
    "transfer_bank_for_deposit": "Bank transfer for secure deposit",
    "dana_ovo_gopay": "DANA, OVO, GoPay, and others",
    "deposit_via_pulsa": "Deposit via prepaid pulsa",
    "instant": "Instant",
    "30_60_seconds": "30 - 60 Seconds",
    "select_qris_provider": "Select QRIS Provider",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "Online",
    "deposit_amount": "Deposit Amount",
    "withdraw_amount": "Withdraw Amount",
    "enter_deposit_amount": "Enter deposit amount",
    "idr": "IDR",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "choose_promo": "Choose Promo (Optional)",
    "choose_promo_optional": "Choose promo (optional)",
    "payment_summary": "Payment Summary",
    "total_deposit": "Deposit Amount:",
    "promo_discount": "Payment Amount:",
    "total": "Total:",
    "confirm_deposit": "Confirm Deposit",
    "rp_0": "Rp 0",
    "select_your_account": "Select Your Account",
    "destination_account": "Destination Account",
    "select_destination": "Select destination account",
    "bank_account_info": "Account Information",
    "bank_name": "Bank Name",
    "account_holder": "Account Holder",
    "recipient_number": "Recipient Number",
    "upload_receipt": "Payment Receipt (Optional)",
    "click_upload_receipt": "Click to upload payment receipt",
    "additional_notes": "Additional Notes (optional)",
    "enter_notes": "No.Ref / Sender Name",
    "select_wallet": "Select E-Wallet",
    "select_ewallet_number": "Select e-wallet number",
    "select_admin_number": "Select Admin Number",
    "recipient_phone": "SN / Recipient Number",
    "enter_recipient_phone": "Enter SN number",
    "withdrawal": "Withdrawal",
    "withdrawal_history": "Withdrawal History",
    "coming_soon": "Coming Soon",
    "profile_settings": "Profile Settings",
    "profile_information": "Profile Information",
    "account_details": "Account Details",
    "account_tier": "Account Tier",
    "change_password": "Change Password",
    "current_password": "Current Password",
    "enter_current_password": "Enter your current password",
    "new_password": "New Password",
    "enter_new_password": "Enter your new password",
    "update_password_instruction": "Update your password",
    "banking_accounts": "Banking Accounts",
    "add_bank": "Add Bank",
    "active": "Active",
    "security": "Security",
    "referral_program": "Referral Program",
    "earn_bonus_from_referrals": "Earn bonuses from your referrals",
    "referral_app_info": "Referral program application with structured form",
    "first_name": "First Name",
    "enter_first_name": "Enter your first name",
    "enter_email": "Enter your email address",
    "enter_phone_number": "Enter your phone number",
    "address": "Address",
    "enter_address": "Enter your full address",
    "bank_ewallet": "Bank/E-Wallet",
    "choose_bank_ewallet": "Choose Your Bank/E-Wallet",
    "identity_file": "Identity File (ID/License/Passport)",
    "click_upload_identity": "Click or drag your identity file here",
    "file_format_limit": "Format: JPG, PNG - Max 10MB",
    "submit_application": "Submit Application",
    "referral_tree": "Referral Tree",
    "total_referral": "Total Referral",
    "no_referrals_yet": "No referrals yet",
    "invite_people_to_join": "Invite people to join and get bonuses",
    "referral_structure_display": "Your referral structure will be displayed here",
    "data_turnover": "Data Turnover",
    "view_performance": "Monitor your playing performance with filters",
    "filter_data": "Filter Data",
    "start_date": "Start Date",
    "end_date": "End Date",
    "category": "Category",
    "provider": "Provider",
    "all_categories": "All Categories",
    "all_providers": "All Providers",
    "search_data": "Search Data",
    "search_results": "Search Results",
    "results": "results",
    "no_data_yet": "No turnover data yet",
    "adjust_filter_to_see_data": "Adjust filter or date to see your turnover data",
    "statistics": "Statistics",
    "cancel": "Cancel",
    "confirm": "Save",
    "send_application": "Send Application",
  },
  th: {
    "sign_in": "เข้าสู่ระบบ",
    "sign_up": "สมัครสมาชิก",
    "home": "หน้าแรก",
    "wallet": "กระเป๋า",
    "hub_kami": "Hub Kami",
    "promotion": "โปรโมชั่น",
    "p2p": "P2P",
    "language": "ภาษา",
    "deposit": "ฝากเงิน",
    "withdraw": "ถอนเงิน",
    "game_hit": "Game Hit",
    "slot": "สล็อต",
    "casino": "คาสิโน",
    "sportsbook": "กีฬา",
    "fishing": "ตกปลา",
    "arcade": "เกมอาร์เคด",
    "cockfighting": "ไก่ชน",
    "togel": "Togel",
    "play": "เล่น",
    "profile": "โปรไฟล์",
    "history": "ประวัติ",
    "cashback": "แคชแบค",
    "earn_money": "สร้างรายได้",
    "credit_point": "เครดิต/คะแนนฟรี",
    "coupon": "คูปอง",
    "randombox": "สุ่มกล่อง",
    "wheel": "วงล้อ",
    "check_in": "เช็คอิน",
    "ranking": "อันดับ",
    "contact_us": "ติดต่อเรา",
    "switch_language": "เปลี่ยนภาษา",
    "manual": "คู่มือ",
    "download_guild": "ดาวน์โหลด Guild",
    "announcement": "🎉 ประกาศ: DEMO Gacor Gaming รับโบนัส & โปรโมชั่นพิเศษวันนี้",
    "free_spins": "💰 ชนะแจ็คพอตใหญ่ด้วย 100 ฟรีสปิน - ฝากเพียง $100",
    "promotion_bonus": "🎁 โปรโมชั่นพิเศษ: โบนัส 50% สำหรับเกมทั้งหมดทุกวัน",
    "welcome_bonus": "⭐ เข้าร่วมตอนนี้และรับ 100 คะแนนฟรีเป็นโบนัสต้อนรับ",
    "search_games": "ค้นหาเกม...",
    "username": "ชื่อผู้ใช้",
    "password": "รหัสผ่าน",
    "confirm_password": "ยืนยันรหัสผ่าน",
    "email": "อีเมล",
    "phone": "เบอร์โทรศัพท์",
    "login": "เข้าสู่ระบบ",
    "register": "ลงทะเบียน",
    "forgot_password": "ลืมรหัสผ่าน",
    "logout": "ออกจากระบบ",
    "have_account": "มีบัญชีอยู่แล้วหรือ",
    "password_mismatch": "รหัสผ่านไม่ตรงกัน",
    "phone_number": "เบอร์โทรศัพท์",
    "please_enter_phone": "กรุณากรอกเบอร์โทรศัพท์ของคุณ",
    "please_enter_password": "กรุณากรอกรหัสผ่านของคุณ",
    "remember_me": "จำฉันไว้",
    "forgot_password_q": "ลืมรหัสผ่าน??",
    "found_problem": "พบปัญหา",
    "contact_customer_service": "ติดต่อฝ่ายบริการลูกค้า",
    "play": "เล่น",
    "credit_balance": "ยอดเงินสดคงเหลือ",
    "wallet": "กระเป๋า",
    "promotion": "โปรโมชั่น",
    "turnover": "มูลค่าการหมุนเวียน",
    "credit_free": "เครดิตฟรี",
    "point_free": "คะแนนฟรี",
    "coupon": "คูปอง",
    "random_box": "สุ่มกล่อง",
    "wheel": "วงล้อ",
    "exchange": "แลกเปลี่ยน",
    "tournament": "การแข่งขัน",
    "deposit_withdraw": "ฝากถอนเงิน",
    "deposit": "ฝากเงิน",
    "withdraw": "ถอนเงิน",
    "deposit_auto": "ฝากเงินอัตโนมัติ",
    "deposit_decimal": "ฝากเศษส่วน",
    "truemoney": "ทรูมันนี่",
    "deposit_confirm_slip": "สลิปยืนยันการฝาก",
    "true_gift": "ของขวัญจริง",
    "deposit_confirm": "ยืนยันการฝาก",
    "line_bot_notification": "แจ้งเตือนบอท Line",
    "normal_withdraw": "การถอนเงินปกติ",
    "max_withdraw": "ถอนสูงสุด",
    "withdraw_to_account": "ถอนเงินของคุณไปยังบัญชี",
    "bio": "ไบโอ",
    "have_questions_readmore": "มีคำถามเพิ่มเติมหรือไม่ อ่านเพิ่มเติม",
    "hub_kami": "Hub Kami",
    "contact_us": "ติดต่อเรา",
    "live_chat_support": "สนับสนุนแชทสด",
    "available_24_7": "มี 24/7",
    "email": "อีเมล",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "เมนูหลัก",
    "income_menu": "เมนูรายได้",
    "event_menu": "เมนูเหตุการณ์",
    "more_menu": "เมนูเพิ่มเติม",
    "logout": "ออกจากระบบ",
    "user_id": "ID ผู้ใช้",
    "balance": "ยอดคงเหลือ",
    "point": "คะแนน",
    "choose_your_bank": "เลือกธนาคารของคุณ",
    "enter_bank_number": "ใส่เลขบัญชีของคุณ",
    "name_lastname": "ชื่อ - นามสกุล",
    "how_do_know_us": "คุณรู้จักเราจากไหน?",
    "choose_receive_bonus": "เลือกว่าจะรับโบนัสหรือไม่",
    "receive": "รับ",
    "not_receive": "ไม่รับ",
    "sign_up_modal": "สมัครสมาชิก",
    "enter_banknumber": "ใส่เลขบัญชีของคุณ",
    "personal_info": "ข้อมูลส่วนตัว",
    "bank_info": "ข้อมูลบัญชีธนาคาร",
    "bank_type": "ประเภทธนาคาร",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "ชื่อบัญชีธนาคาร",
    "account_number": "หมายเลขบัญชี",
    "banking": "ธนาคาร",
    "choose_deposit_method": "เลือกวิธีการฝากเงิน",
    "choose_payment_method": "เลือกวิธีการชำระเงินที่คุณต้องการ",
    "qris": "QRIS",
    "bank_transfer": "โอนธนาคาร",
    "e_wallet": "กระเป๋าเงินดิจิตอล",
    "pulsa": "Pulsa",
    "scan_qr_instant": "สแกน QR code เพื่อฝากเงินทันที",
    "transfer_bank_for_deposit": "โอนธนาคารเพื่อฝากเงินที่ปลอดภัย",
    "dana_ovo_gopay": "DANA, OVO, GoPay และอื่น ๆ",
    "deposit_via_pulsa": "ฝากเงินผ่าน Pulsa แบบเติมเงิน",
    "instant": "ทันที",
    "30_60_seconds": "30 - 60วัน",
    "select_qris_provider": "เลือกผู้ให้บริการ QRIS",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "ออนไลน์",
    "deposit_amount": "จำนวนเงินฝาก",
    "enter_deposit_amount": "ป้อนจำนวนเงินฝาก",
    "idr": "IDR",
    "minimum": "ขั้นต่ำ",
    "maximum": "สูงสุด",
    "choose_promo": "เลือกโปรโมชั่น (ไม่บังคับ)",
    "choose_promo_optional": "เลือกโปรโมชั่น (ไม่บังคับ)",
    "payment_summary": "สรุปการชำระเงิน",
    "total_deposit": "จำนวนเงินฝาก:",
    "promo_discount": "จำนวนการชำระเงิน:",
    "total": "รวม:",
    "confirm_deposit": "ยืนยันการฝากเงิน",
    "rp_0": "Rp 0",
    "select_your_account": "เลือกบัญชีของคุณ",
    "destination_account": "บัญชีปลายทาง",
    "select_destination": "เลือกบัญชีปลายทาง",
    "bank_account_info": "ข้อมูลบัญชี",
    "bank_name": "ชื่อธนาคาร",
    "account_holder": "ผู้ถือบัญชี",
    "recipient_number": "หมายเลขผู้รับ",
    "upload_receipt": "ใบเสร็จการชำระเงิน (ไม่บังคับ)",
    "click_upload_receipt": "คลิกเพื่ออัปโหลดใบเสร็จการชำระเงิน",
    "additional_notes": "หมายเหตุเพิ่มเติม (ไม่บังคับ)",
    "enter_notes": "No.Ref / ชื่อผู้ส่ง",
    "select_wallet": "เลือกกระเป๋าเงินดิจิตอล",
    "select_ewallet_number": "เลือกหมายเลขกระเป๋าเงินดิจิตอล",
    "select_admin_number": "เลือกหมายเลขแอดมิน",
    "recipient_phone": "หมายเลข SN / หมายเลขผู้รับ",
    "enter_recipient_phone": "ป้อนหมายเลข SN",
    "withdrawal": "การถอนเงิน",
    "withdrawal_history": "ประวัติการถอนเงิน",
    "coming_soon": "เร็ว ๆ นี้",
    "profile_information": "ข้อมูลโปรไฟล์",
    "coming_soon": "เร็ว ๆ นี้",
    "profile_settings": "การตั้งค่าโปรไฟล์",
    "profile_information": "ข้อมูลโปรไฟล์",
    "account_details": "รายละเอียดบัญชี",
    "account_tier": "ระดับบัญชี",
    "change_password": "เปลี่ยนรหัสผ่าน",
    "current_password": "รหัสผ่านปัจจุบัน",
    "enter_current_password": "ป้อนรหัสผ่านปัจจุบัน",
    "new_password": "รหัสผ่านใหม่",
    "enter_new_password": "ป้อนรหัสผ่านใหม่",
    "update_password_instruction": "อัปเดตรหัสผ่านของคุณ",
    "banking_accounts": "บัญชีธนาคาร",
    "add_bank": "เพิ่มธนาคาร",
    "active": "ใช้งานอยู่",
    "security": "ความปลอดภัย",
    "referral_program": "โปรแกรมการอ้างอิง",
    "earn_bonus_from_referrals": "รับโบนัสจากการอ้างอิงของคุณ",
    "referral_app_info": "แอปพลิเคชันโปรแกรมการอ้างอิงพร้อมฟอร์มที่มีโครงสร้าง",
    "first_name": "ชื่อ",
    "enter_first_name": "ป้อนชื่อของคุณ",
    "enter_email": "ป้อนที่อยู่อีเมลของคุณ",
    "enter_phone_number": "ป้อนเบอร์โทรศัพท์ของคุณ",
    "address": "ที่อยู่",
    "enter_address": "ป้อนที่อยู่เต็ม",
    "bank_ewallet": "ธนาคาร/กระเป๋าเงินดิจิตอล",
    "choose_bank_ewallet": "เลือกธนาคารหรือกระเป๋าเงินดิจิตอล",
    "identity_file": "ไฟล์ประจำตัว (ID/ใบขับขี่/พาสปอร์ต)",
    "click_upload_identity": "คลิกหรือลากไฟล์ประจำตัวของคุณที่นี่",
    "file_format_limit": "รูปแบบ: JPG, PNG - ขนาดสูงสุด 10MB",
    "submit_application": "ส่งใบสมัคร",
    "referral_tree": "ต้นไม้การอ้างอิง",
    "total_referral": "จำนวนการอ้างอิงทั้งหมด",
    "no_referrals_yet": "ยังไม่มีการอ้างอิง",
    "invite_people_to_join": "เชิญคนให้เข้าร่วมและรับโบนัส",
    "referral_structure_display": "โครงสร้างการอ้างอิงของคุณจะแสดงที่นี่",
    "data_turnover": "ข้อมูลการหมุนเวียน",
    "view_performance": "ตรวจสอบประสิทธิภาพการเล่นของคุณด้วยตัวกรอง",
    "filter_data": "ข้อมูลตัวกรอง",
    "start_date": "วันที่เริ่มต้น",
    "end_date": "วันสิ้นสุด",
    "category": "หมวดหมู่",
    "provider": "ผู้ให้บริการ",
    "all_categories": "หมวดหมู่ทั้งหมด",
    "all_providers": "ผู้ให้บริการทั้งหมด",
    "search_data": "ค้นหาข้อมูล",
    "search_results": "ผลการค้นหา",
    "results": "ผล",
    "no_data_yet": "ยังไม่มีข้อมูลการหมุนเวียน",
    "adjust_filter_to_see_data": "ปรับตัวกรองหรือวันที่เพื่อดูข้อมูลการหมุนเวียนของคุณ",
    "statistics": "สถิติ",
    "cancel": "ยกเลิก",
    "confirm": "บันทึก",
    "send_application": "Send Application",
  },
  zh: {
    "sign_in": "登录",
    "sign_up": "注册",
    "home": "主页",
    "wallet": "钱包",
    "hub_kami": "Hub Kami",
    "promotion": "促销",
    "p2p": "P2P",
    "language": "语言",
    "deposit": "充值",
    "withdraw": "提款",
    "game_hit": "热门游戏",
    "slot": "老虎机",
    "casino": "赌场",
    "sportsbook": "体育",
    "fishing": "捕鱼",
    "arcade": "街机",
    "cockfighting": "斗鸡",
    "togel": "彩票",
    "play": "玩",
    "profile": "资料",
    "history": "历史",
    "cashback": "返利",
    "earn_money": "赚钱",
    "credit_point": "免费积分",
    "coupon": "优惠券",
    "randombox": "随机箱",
    "wheel": "转轮",
    "check_in": "签到",
    "ranking": "排名",
    "contact_us": "联系我们",
    "switch_language": "切换语言",
    "manual": "手册",
    "download_guild": "下载",
    "announcement": "🎉 公告：DEMO Gacor Gaming 获得特别奖励和促销",
    "free_spins": "💰 赢取 100 次免费旋转 - 仅存款 $100",
    "promotion_bonus": "🎁 特别促销：所有游戏每天 50% 奖励",
    "welcome_bonus": "⭐ 立即加入并获得 100 免费积分作为欢迎奖励",
    "search_games": "搜索游戏...",
    "username": "用户名",
    "password": "密码",
    "confirm_password": "确认密码",
    "email": "电子邮件",
    "phone": "电话号码",
    "login": "登录",
    "register": "注册",
    "forgot_password": "忘记密码",
    "logout": "登出",
    "have_account": "已有账户",
    "password_mismatch": "密码不匹配",
    "phone_number": "电话号码",
    "please_enter_phone": "请输入您的电话号码",
    "please_enter_password": "请输入您的密码",
    "remember_me": "记住我",
    "forgot_password_q": "忘记密码??",
    "found_problem": "发现问题",
    "contact_customer_service": "联系客户服务",
    "play": "玩",
    "credit_balance": "信用余额",
    "wallet": "钱包",
    "promotion": "促销",
    "turnover": "营业额",
    "credit_free": "免费积分",
    "point_free": "免费积分",
    "coupon": "优惠券",
    "random_box": "随机箱",
    "wheel": "转轮",
    "exchange": "兑换",
    "tournament": "竞赛",
    "deposit_withdraw": "充值提款",
    "deposit": "充值",
    "withdraw": "提款",
    "deposit_auto": "自动充值",
    "deposit_decimal": "小数充值",
    "truemoney": "真钱",
    "deposit_confirm_slip": "充值确认单",
    "true_gift": "真礼物",
    "deposit_confirm": "充值确认",
    "line_bot_notification": "Line 机器人通知",
    "normal_withdraw": "正常提款",
    "max_withdraw": "最大提款",
    "withdraw_to_account": "提现到账户",
    "bio": "生物",
    "have_questions_readmore": "还有其他问题？阅读更多",
    "hub_kami": "Hub Kami",
    "contact_us": "联系我们",
    "live_chat_support": "实时聊天支持",
    "available_24_7": "24/7 可用",
    "email": "电子邮件",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "主菜单",
    "income_menu": "收入菜单",
    "event_menu": "事件菜单",
    "more_menu": "更多菜单",
    "logout": "登出",
    "user_id": "用户ID",
    "balance": "余额",
    "point": "点",
    "choose_your_bank": "选择您的银行",
    "enter_bank_number": "输入您的银行号码",
    "name_lastname": "名字 - 姓氏",
    "how_do_know_us": "你从哪里认识我们的？",
    "choose_receive_bonus": "选择是否接收奖金",
    "receive": "接收",
    "not_receive": "不接收",
    "sign_up_modal": "注册",
    "enter_banknumber": "输入您的银行号码",
    "personal_info": "个人信息",
    "bank_info": "银行账户信息",
    "bank_type": "银行类型",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "银行账户名称",
    "account_number": "账户号码",
    "banking": "银行业务",
    "choose_deposit_method": "选择存款方式",
    "choose_payment_method": "选择您想要的付款方式",
    "qris": "QRIS",
    "bank_transfer": "银行转账",
    "e_wallet": "电子钱包",
    "pulsa": "Pulsa",
    "scan_qr_instant": "扫描二维码进行即时存款",
    "transfer_bank_for_deposit": "银行转账以安全存款",
    "dana_ovo_gopay": "DANA、OVO、GoPay 等",
    "deposit_via_pulsa": "通过预付费 Pulsa 存款",
    "instant": "即时",
    "30_60_seconds": "30 - 60天",
    "select_qris_provider": "选择 QRIS 提供商",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "在线",
    "deposit_amount": "存款金额",
    "enter_deposit_amount": "输入存款金额",
    "idr": "IDR",
    "minimum": "最少",
    "maximum": "最多",
    "choose_promo": "选择促销（可选）",
    "choose_promo_optional": "选择促销（可选）",
    "payment_summary": "付款摘要",
    "total_deposit": "存款金额：",
    "promo_discount": "支付金额：",
    "total": "总计：",
    "confirm_deposit": "确认存款",
    "rp_0": "Rp 0",
    "select_your_account": "选择您的账户",
    "destination_account": "目标账户",
    "select_destination": "选择目标账户",
    "bank_account_info": "账户信息",
    "bank_name": "银行名称",
    "account_holder": "账户持有人",
    "recipient_number": "收件人号码",
    "upload_receipt": "支付凭证（可选）",
    "click_upload_receipt": "点击上传支付凭证",
    "additional_notes": "附加说明（可选）",
    "enter_notes": "No.Ref / 发件人名称",
    "select_wallet": "选择电子钱包",
    "select_ewallet_number": "选择电子钱包号码",
    "select_admin_number": "选择管理员号码",
    "recipient_phone": "SN / 收件人号码",
    "enter_recipient_phone": "输入 SN 号码",
    "withdrawal": "提现",
    "withdrawal_history": "提现历史",
    "coming_soon": "近日推出",
    "profile_settings": "个人资料设置",
    "profile_information": "个人资料信息",
    "account_details": "账户详情",
    "account_tier": "账户等级",
    "change_password": "更改密码",
    "current_password": "当前密码",
    "enter_current_password": "输入当前密码",
    "new_password": "新密码",
    "enter_new_password": "输入新密码",
    "update_password_instruction": "更新您的密码",
    "banking_accounts": "银行账户",
    "add_bank": "添加银行",
    "active": "活跃",
    "security": "安全",
    "referral_program": "推荐计划",
    "earn_bonus_from_referrals": "从推荐中赚取奖金",
    "referral_app_info": "推荐计划应用程序带有结构化表单",
    "first_name": "名字",
    "enter_first_name": "输入您的名字",
    "enter_email": "输入您的电子邮件地址",
    "enter_phone_number": "输入您的电话号码",
    "address": "地址",
    "enter_address": "输入您的完整地址",
    "bank_ewallet": "银行/电子钱包",
    "choose_bank_ewallet": "选择您的银行/电子钱包",
    "identity_file": "身份文件（ID/驾照/护照）",
    "click_upload_identity": "点击或拖动您的身份文件到此处",
    "file_format_limit": "格式：JPG、PNG - 最大 10MB",
    "submit_application": "提交申请",
    "referral_tree": "推荐树",
    "total_referral": "总推荐数",
    "no_referrals_yet": "还没有推荐",
    "invite_people_to_join": "邀请人们加入并获得奖金",
    "referral_structure_display": "您的推荐结构将在此显示",
    "data_turnover": "数据营业额",
    "view_performance": "使用过滤器监控您的游戏性能",
    "filter_data": "筛选数据",
    "start_date": "开始日期",
    "end_date": "结束日期",
    "category": "类别",
    "provider": "提供商",
    "all_categories": "所有类别",
    "all_providers": "所有提供商",
    "search_data": "搜索数据",
    "search_results": "搜索结果",
    "results": "结果",
    "no_data_yet": "还没有营业额数据",
    "adjust_filter_to_see_data": "调整筛选器或日期以查看您的营业额数据",
    "statistics": "统计",
    "cancel": "取消",
    "confirm": "保存",
    "send_application": "Send Application",
  },
  ja: {
    "sign_in": "ログイン",
    "sign_up": "登録",
    "home": "ホーム",
    "wallet": "ウォレット",
    "hub_kami": "Hub Kami",
    "promotion": "プロモーション",
    "p2p": "P2P",
    "language": "言語",
    "deposit": "入金",
    "withdraw": "出金",
    "game_hit": "人気ゲーム",
    "slot": "スロット",
    "casino": "カジノ",
    "sportsbook": "スポーツ",
    "fishing": "釣り",
    "arcade": "アーケード",
    "cockfighting": "闘鶏",
    "togel": "トーゲル",
    "play": "プレイ",
    "profile": "プロフィール",
    "history": "履歴",
    "cashback": "キャッシュバック",
    "earn_money": "収益を得る",
    "credit_point": "クレジット/ポイント無料",
    "coupon": "クーポン",
    "randombox": "ランダムボックス",
    "wheel": "ホイール",
    "check_in": "チェックイン",
    "ranking": "ランキング",
    "contact_us": "お問い合わせ",
    "switch_language": "言語を変更",
    "manual": "マニュアル",
    "download_guild": "ダウンロード",
    "announcement": "🎉 お知らせ：DEMO Gacor Gaming 特別ボーナス＆プロモーション",
    "free_spins": "💰 100フリースピンで大勝利 - $100のみの入金",
    "promotion_bonus": "🎁 特別プロモーション：毎日すべてのゲームで50%ボーナス",
    "welcome_bonus": "⭐ 今すぐ参加して、ウェルカムボーナスとして100無料ポイントを獲得",
    "search_games": "ゲームを検索...",
    "username": "ユーザー名",
    "password": "パスワード",
    "confirm_password": "パスワード確認",
    "email": "メール",
    "phone": "電話番号",
    "login": "ログイン",
    "register": "登録",
    "forgot_password": "パスワード忘れ",
    "logout": "ログアウト",
    "have_account": "アカウントをお持ちですか？",
    "password_mismatch": "パスワードが一致しません",
    "phone_number": "電話番号",
    "please_enter_phone": "お電話番号をご入力ください",
    "please_enter_password": "パスワードを入力してください",
    "remember_me": "私を思い出して",
    "forgot_password_q": "パスワードをお忘れですか??",
    "found_problem": "問題が見つかりました",
    "contact_customer_service": "カスタマーサービスに連絡",
    "play": "プレイ",
    "credit_balance": "クレジット残高",
    "wallet": "ウォレット",
    "promotion": "プロモーション",
    "turnover": "営業額",
    "credit_free": "クレジット無料",
    "point_free": "ポイント無料",
    "coupon": "クーポン",
    "random_box": "ランダムボックス",
    "wheel": "ホイール",
    "exchange": "交換",
    "tournament": "トーナメント",
    "deposit_withdraw": "入金・出金",
    "deposit": "入金",
    "withdraw": "出金",
    "deposit_auto": "自動入金",
    "deposit_decimal": "入金小数",
    "truemoney": "トゥルーマネー",
    "deposit_confirm_slip": "入金確認書",
    "true_gift": "本当の贈り物",
    "deposit_confirm": "入金確認",
    "line_bot_notification": "Line ボット通知",
    "normal_withdraw": "通常出金",
    "max_withdraw": "最大出金",
    "withdraw_to_account": "アカウントにお金を引き出す",
    "bio": "バイオ",
    "have_questions_readmore": "ご不明な点がございますか？詳細を読む",
    "hub_kami": "Hub Kami",
    "contact_us": "お問い合わせ",
    "live_chat_support": "ライブチャットサポート",
    "available_24_7": "24/7 利用可能",
    "email": "メール",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "メインメニュー",
    "income_menu": "収入メニュー",
    "event_menu": "イベントメニュー",
    "more_menu": "その他メニュー",
    "logout": "ログアウト",
    "user_id": "ユーザーID",
    "balance": "残高",
    "point": "ポイント",
    "choose_your_bank": "銀行を選択",
    "enter_bank_number": "銀行番号を入力",
    "name_lastname": "名前 - 苗字",
    "how_do_know_us": "あなたはどこから私たちを知っていますか？",
    "choose_receive_bonus": "ボーナスを受け取るかどうかを選択",
    "receive": "受け取る",
    "not_receive": "受け取らない",
    "sign_up_modal": "登録",
    "enter_banknumber": "銀行番号を入力してください",
    "personal_info": "個人情報",
    "bank_info": "銀行口座情報",
    "bank_type": "銀行の種類",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "銀行口座名",
    "account_number": "口座番号",
    "banking": "銀行",
    "choose_deposit_method": "入金方法を選択",
    "choose_payment_method": "お好みの支払い方法を選択してください",
    "qris": "QRIS",
    "bank_transfer": "銀行振込",
    "e_wallet": "電子ウォレット",
    "pulsa": "Pulsa",
    "scan_qr_instant": "QRコードをスキャンして即座に入金",
    "transfer_bank_for_deposit": "銀行振込で安全に入金",
    "dana_ovo_gopay": "DANA、OVO、GoPay など",
    "deposit_via_pulsa": "プリペイド Pulsa 経由で入金",
    "instant": "即座",
    "30_60_seconds": "30 - 60日",
    "select_qris_provider": "QRIS プロバイダーを選択",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "オンライン",
    "deposit_amount": "入金額",
    "enter_deposit_amount": "入金額を入力",
    "idr": "IDR",
    "minimum": "最小",
    "maximum": "最大",
    "choose_promo": "プロモーションを選択（オプション）",
    "choose_promo_optional": "プロモーションを選択（オプション）",
    "payment_summary": "支払いサマリー",
    "total_deposit": "入金額：",
    "promo_discount": "支払い額：",
    "total": "合計：",
    "confirm_deposit": "入金を確認",
    "rp_0": "Rp 0",
    "select_your_account": "アカウントを選択",
    "destination_account": "宛先アカウント",
    "select_destination": "宛先アカウントを選択",
    "bank_account_info": "アカウント情報",
    "bank_name": "銀行名",
    "account_holder": "口座名義人",
    "recipient_number": "受取人番号",
    "upload_receipt": "支払い領収書（オプション）",
    "click_upload_receipt": "クリックして支払い領収書をアップロード",
    "additional_notes": "追加メモ（オプション）",
    "enter_notes": "No.Ref / 送信者名",
    "select_wallet": "電子ウォレットを選択",
    "select_ewallet_number": "電子ウォレット番号を選択",
    "select_admin_number": "管理者番号を選択",
    "recipient_phone": "SN / 受取人番号",
    "enter_recipient_phone": "SN 番号を入力",
    "withdrawal": "出金",
    "withdrawal_history": "出金履歴",
    "coming_soon": "近日推出",
    "profile_settings": "プロフィール設定",
    "profile_information": "プロフィール情報",
    "account_details": "アカウント詳細",
    "account_tier": "アカウントティア",
    "change_password": "パスワード変更",
    "current_password": "現在のパスワード",
    "enter_current_password": "現在のパスワードを入力",
    "new_password": "新しいパスワード",
    "enter_new_password": "新しいパスワードを入力",
    "update_password_instruction": "パスワードを更新する",
    "banking_accounts": "銀行口座",
    "add_bank": "銀行を追加",
    "active": "アクティブ",
    "security": "セキュリティ",
    "referral_program": "紹介プログラム",
    "earn_bonus_from_referrals": "紹介からボーナスを獲得",
    "referral_app_info": "構造化フォーム付き紹介プログラムアプリケーション",
    "first_name": "名前",
    "enter_first_name": "名前を入力",
    "enter_email": "メールアドレスを入力",
    "enter_phone_number": "電話番号を入力",
    "address": "住所",
    "enter_address": "完全な住所を入力",
    "bank_ewallet": "銀行/電子ウォレット",
    "choose_bank_ewallet": "銀行/電子ウォレットを選択",
    "identity_file": "身分証明書ファイル（ID/運転免許証/パスポート）",
    "click_upload_identity": "ここをクリックまたはドラッグして身分証明書をアップロード",
    "file_format_limit": "形式：JPG、PNG - 最大 10MB",
    "submit_application": "申請を提出",
    "referral_tree": "紹介ツリー",
    "total_referral": "総紹介数",
    "no_referrals_yet": "まだ紹介がありません",
    "invite_people_to_join": "人々を招待して参加させ、ボーナスを獲得",
    "referral_structure_display": "紹介構造がここに表示されます",
    "data_turnover": "データ営業額",
    "view_performance": "フィルターを使用してプレイパフォーマンスを監視",
    "filter_data": "データをフィルター",
    "start_date": "開始日",
    "end_date": "終了日",
    "category": "カテゴリー",
    "provider": "プロバイダー",
    "all_categories": "すべてのカテゴリー",
    "all_providers": "すべてのプロバイダー",
    "search_data": "データを検索",
    "search_results": "検索結果",
    "results": "結果",
    "no_data_yet": "まだ営業額データがありません",
    "adjust_filter_to_see_data": "フィルターまたは日付を調整して営業額データを表示",
    "statistics": "統計",
    "cancel": "キャンセル",
    "confirm": "保存",
    "send_application": "Send Application",
  },
  km: {
    "sign_in": "ចូលប្រព័ន្ធ",
    "sign_up": "ចុះឈ្មោះ",
    "home": "ទំព័រដើម",
    "wallet": "កាបូប",
    "hub_kami": "Hub Kami",
    "promotion": "ការផ្សព្វផ្សាយ",
    "p2p": "P2P",
    "language": "ភាសា",
    "deposit": "ដាក់ប្រាក់",
    "withdraw": "ដកប្រាក់",
    "game_hit": "ល្បែងពេញនិយម",
    "slot": "ល្បែងស្លត",
    "casino": "កាស៊ីណូ",
    "sportsbook": "ល្បែងក្រីឌា",
    "fishing": "ល្បែងនេសាទ",
    "arcade": "ល្បែង Arcade",
    "cockfighting": "ល្បែងសិប្បនិមិត្ត",
    "togel": "ល្បែង Togel",
    "play": "លេង",
    "profile": "ប្រវត្តិរូប",
    "history": "ប្រវត្តិ",
    "cashback": "ប្រាក់ឆ្លងំុ",
    "earn_money": "រកលុយ",
    "credit_point": "ឥណទានឥតគិតថ្លៃ",
    "coupon": "ឃ្វូច",
    "randombox": "ប្រអប់ចៃដន្យ",
    "wheel": "កង្វល់",
    "check_in": "ឆែក",
    "ranking": "ចំណាត់ថ្នាក់",
    "contact_us": "ទាក់ទងយើងខ្ញុំ",
    "switch_language": "ផ្លាស់ប្តូរភាសា",
    "manual": "ម៉ាន៌អែល",
    "download_guild": "ទាញយក Guild",
    "announcement": "🎉 ដំណឹង: DEMO Gacor Gaming ទទួលបានបន្ថែម & ការផ្សព្វផ្សាយពិសេស",
    "free_spins": "💰 ឈ្នះលុយច្រើនដោយ 100 ចលនាឥតគិតថ្លៃ - ដាក់ប្រាក់តែ $100",
    "promotion_bonus": "🎁 ការផ្សព្វផ្សាយពិសេស: បន្ថែម 50% សម្រាប់ល្បែងទាំងអស់រៀងរាល់ថ្ងៃ",
    "welcome_bonus": "⭐ ចូលរួម ហើយទទួលបាន 100 ពិន្ទុឥតគិតថ្លៃក្នុងនាមជាបន្ថែមស្វាគមន៍",
    "search_games": "ស្វែងរកល្បែង...",
    "username": "ឈ្មោះអ្នកប្រើប្រាស់",
    "password": "ពាក្យសម្ងាត់",
    "confirm_password": "បញ្ជាក់ពាក្យសម្ងាត់",
    "email": "អ៊ីមែល",
    "phone": "លេខទូរស័ព្ទ",
    "login": "ចូលប្រព័ន្ធ",
    "register": "ចុះឈ្មោះ",
    "forgot_password": "ភ្លេចពាក្យសម្ងាត់",
    "logout": "ច្រាលចេញ",
    "have_account": "មានគណនីរួចហើយ",
    "password_mismatch": "ពាក្យសម្ងាត់មិនដូចគ្នា",
    "phone_number": "លេខទូរស័ព្ទ",
    "please_enter_phone": "សូមបញ្ចូលលេខទូរស័ព្ទរបស់អ្នក",
    "please_enter_password": "សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក",
    "remember_me": "ចូលចាំខ្ញុំ",
    "forgot_password_q": "ភ្លេចពាក្យសម្ងាត់??",
    "found_problem": "រកឃើញបញ្ហា",
    "contact_customer_service": "ទាក់ទងសេវាកម្មអតិថិជន",
    "play": "លេង",
    "credit_balance": "ចំនួនលុយឥណទាន",
    "wallet": "កាបូប",
    "promotion": "ការផ្សព្វផ្សាយ",
    "turnover": "ចំនួនលុយវិល",
    "credit_free": "ឥណទានឥតគិតថ្លៃ",
    "point_free": "ពិន្ទុឥតគិតថ្លៃ",
    "coupon": "ឃ្វូច",
    "random_box": "ប្រអប់ចៃដន្យ",
    "wheel": "កង្វល់",
    "exchange": "ផ្លាស់ប្តូរ",
    "tournament": "ការប្រកួតប្រជែង",
    "deposit_withdraw": "ដាក់ប្រាក់ - ដកប្រាក់",
    "deposit": "ដាក់ប្រាក់",
    "withdraw": "ដកប្រាក់",
    "deposit_auto": "ដាក់ប្រាក់ដោយស្វయ័ត",
    "deposit_decimal": "ដាក់ប្រាក់ទសភាគ",
    "truemoney": "ប្រាក់ពិតប្រាកដ",
    "deposit_confirm_slip": "សលិកបង្ហាញការដាក់ប្រាក់",
    "true_gift": "ការយល់ព្រម​ពិតប្រាកដ",
    "deposit_confirm": "បង្ហាញការដាក់ប្រាក់",
    "line_bot_notification": "ការជូនដំណឹងផ្នែក Line",
    "normal_withdraw": "ការដកប្រាក់ធម្មតា",
    "max_withdraw": "ដកប្រាក់អតិបរមា",
    "withdraw_to_account": "ដកលុយរបស់អ្នកទៅគណនី",
    "bio": "ជីវប្រវត្តិ",
    "have_questions_readmore": "មានសំណួរលម្អិតទៀតទេ? អានលម្អិត",
    "hub_kami": "Hub Kami",
    "contact_us": "ទាក់ទងយើងខ្ញុំ",
    "live_chat_support": "ការគាំទ័របន្ទាត់ផ្ទាល់ខ្លួន",
    "available_24_7": "មាន 24/7",
    "email": "អ៊ីមែល",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "ម៉េនុយមេ",
    "income_menu": "ម៉េនុយប្រាក់ចំណូល",
    "event_menu": "ម៉េនុយព្រឹត្តិការណ៍",
    "more_menu": "ម៉េនុយលម្អិតជាង",
    "logout": "ច្រាលចេញ",
    "user_id": "លេខសម្គាល់អ្នកប្រើប្រាស់",
    "balance": "ចំនួនលុយ",
    "point": "ចំណុច",
    "choose_your_bank": "ជ្រើសរើសធនាคាររបស់អ្នក",
    "enter_bank_number": "បញ្ចូលលេខគណនីធនាម៉ាគ់របស់អ្នក",
    "name_lastname": "ឈ្មោះ - នាមខ្លួន",
    "how_do_know_us": "តើអ្នកដឹងពីយើងដោយរបៀបណា?",
    "choose_receive_bonus": "ជ្រើសរើសថាតើអ្នកចង់ទទួលបានប្រាក់보너스ឬឫទេ",
    "receive": "ទទួល",
    "not_receive": "មិនទទួល",
    "sign_up_modal": "ចុះឈ្មោះ",
    "enter_banknumber": "បញ្ចូលលេខធនាម៉ាគ់របស់អ្នក",
    "personal_info": "ព័ត៌មានផ្ទាល់ខ្លួន",
    "bank_info": "ព័ត៌មានគណនីធនាគារ",
    "bank_type": "ប្រភេទធនាគារ",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "ឈ្មោះគណនីធនាគារ",
    "account_number": "លេខគណនី",
    "banking": "ធនាគារ",
    "choose_deposit_method": "ជ្រើសរើសវិធីសាស្ត្របង្កាន់ដាក់ប្រាក់",
    "choose_payment_method": "ជ្រើសរើសវិធីសាស្ត្របង្កាន់ប្រាក់របស់អ្នក",
    "qris": "QRIS",
    "bank_transfer": "ផ្ទេរលុយធនាគារ",
    "e_wallet": "កាបូបលុយឌីជីថល",
    "pulsa": "Pulsa",
    "scan_qr_instant": "ស្កេន QR code ដើម្បីដាក់ប្រាក់ភ្លាមៗ",
    "transfer_bank_for_deposit": "ផ្ទេរលុយធនាគារដើម្បីដាក់ប្រាក់សុវត្ថិភាព",
    "dana_ovo_gopay": "DANA, OVO, GoPay និងលទ្ធផលផ្សេងទៀត",
    "deposit_via_pulsa": "ដាក់ប្រាក់ដោយ Pulsa ដែលបង់ច្រាសមុន",
    "instant": "ភ្លាមៗ",
    "30_60_seconds": "30 - 60ថ្ងៃ",
    "select_qris_provider": "ជ្រើសរើសក្រុមហ៊ុនផ្តល់ប្រឹក្សាយោបល់ QRIS",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "តាមលើបណ្តាញ",
    "deposit_amount": "ចំនួនលុយដាក់",
    "enter_deposit_amount": "បញ្ចូលចំនួនលុយដាក់",
    "idr": "IDR",
    "minimum": "អប្បបរមា",
    "maximum": "អតិបរមា",
    "choose_promo": "ជ្រើសរើស Promo (ច្រើន)",
    "choose_promo_optional": "ជ្រើសរើស Promo (ច្រើន)",
    "payment_summary": "សង្ខេបការបង់ប្រាក់",
    "total_deposit": "ចំនួនលុយដាក់:",
    "promo_discount": "ចំនួនលុយបង់:",
    "total": "សរុប:",
    "confirm_deposit": "ផ្ទៀងផ្ទាត់ការដាក់ប្រាក់",
    "rp_0": "Rp 0",
    "select_your_account": "ជ្រើសរើសគណនីរបស់អ្នក",
    "destination_account": "គណនីទម្ងន់",
    "select_destination": "ជ្រើសរើសគណនីទម្ងន់",
    "bank_account_info": "ព័ត៌មានគណនី",
    "bank_name": "ឈ្មោះធនាគារ",
    "account_holder": "ម្ចាស់គណនី",
    "recipient_number": "លេខបុគ្គលទទួលយក",
    "upload_receipt": "ក្រលាបង្វង (ច្រើន)",
    "click_upload_receipt": "ចុចដើម្បីផ្ទុកក្រលាបង្វង",
    "additional_notes": "ចំណា붑សម្ពាធ (ច្រើន)",
    "enter_notes": "No.Ref / ឈ្មោះអ្នកផ្ញើ",
    "select_wallet": "ជ្រើសរើសកាបូបលុយឌីជីថល",
    "select_ewallet_number": "ជ្រើសរើសលេខកាបូបលុយឌីជីថល",
    "select_admin_number": "ជ្រើសរើសលេខគ្រប់គ្រង",
    "recipient_phone": "SN / លេខបុគ្គលទទួលយក",
    "enter_recipient_phone": "បញ្ចូលលេខ SN",
    "withdrawal": "ដកប្រាក់",
    "withdrawal_history": "ប្រវត្តិការដកប្រាក់",
    "coming_soon": "មកដោះស្រាយឆាប់ ៗ",
    "profile_settings": "ការកំណត់ប្រវត្តិរូប",
    "profile_information": "ព័ត៌មានប្រវត្តិរូប",
    "account_details": "បង្ហាញលម្អិតគណនី",
    "account_tier": "ថ្នាក់គណនី",
    "change_password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
    "current_password": "ពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "enter_current_password": "បញ្ចូលពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "new_password": "ពាក្យសម្ងាត់ថ្មី",
    "enter_new_password": "បញ្ចូលពាក្យសម្ងាត់ថ្មី",
    "update_password_instruction": "កែប្រែពាក្យសម្ងាត់របស់អ្នក",
    "banking_accounts": "គណនីធនាគារ",
    "add_bank": "បន្ថែមធនាគារ",
    "active": "សកម្ម",
    "security": "សុវត្ថិភាព",
    "referral_program": "កម្មវិធីឯកសារយោង",
    "earn_bonus_from_referrals": "រកលុយប្រាក់បន្ថែមពីឯកសារយោងរបស់អ្នក",
    "referral_app_info": "ដាក់ពាក្យដាក់ពាក្យកម្មវិធីឯកសារយោងដែលមានម៉ាកឌ្រាយ",
    "first_name": "ឈ្មោះ",
    "enter_first_name": "បញ្ចូលឈ្មោះរបស់អ្នក",
    "enter_email": "បញ្ចូលលម្អិត​អ៊ីមែល​របស់អ្នក",
    "enter_phone_number": "បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក",
    "address": "ពិសា",
    "enter_address": "បញ្ចូលលម្អិតពិសារបស់អ្នក",
    "bank_ewallet": "ធនាគារ/ក្ដារទូរពិន",
    "choose_bank_ewallet": "ជ្រើសរើសធនាគារ/ក្ដារទូរពិនរបស់អ្នក",
    "identity_file": "ឯកសារបញ្ញាណ (ID/ប័ណ្ណបើកបរ/លិខិតឆ្លងដែន)",
    "click_upload_identity": "ចុចឬទាញឯកសារបញ្ញាណរបស់អ្នកនៅទីនេះ",
    "file_format_limit": "ទម្រង់: JPG, PNG - ដែនកំណត់ 10MB",
    "submit_application": "ដាក់ពាក្យដាក់ពាក្យ",
    "referral_tree": "ឈើឯកសារយោង",
    "total_referral": "ចំនួនឯកសារយោងសរុប",
    "no_referrals_yet": "មិនទាន់មានឯកសារយោង",
    "invite_people_to_join": "ស្វាគមន៍មនុស្សឱ្យចូលរួមហើយរកលុយប្រាក់បន្ថែម",
    "referral_structure_display": "រចនាសម្ព័ន្ធឯកសារយោងរបស់អ្នកនឹងបង្ហាញនៅទីនេះ",
    "data_turnover": "ទិន្នន័យលំហូរ",
    "view_performance": "ឈានដល់មតិយោបល់លេង",
    "filter_data": "ដាក់ដង្ហើមទិន្នន័យ",
    "start_date": "ថ្ងៃចាប់ផ្តើម",
    "end_date": "ថ្ងៃបញ្ចប់",
    "category": "ក្រុម",
    "provider": "អ្នកផ្តល់",
    "all_categories": "ក្រុមទាំងអស់",
    "all_providers": "អ្នកផ្តល់ទាំងអស់",
    "search_data": "ស្វែងរកទិន្នន័យ",
    "search_results": "លទ្ធផលស្វែងរក",
    "results": "លទ្ធផល",
    "no_data_yet": "មិនទាន់មានទិន្នន័យលំហូរ",
    "adjust_filter_to_see_data": "កែប្រែដង្ហើមឬថ្ងៃដើម្បីមើលទិន្នន័យលំហូររបស់អ្នក",
    "statistics": "ស្ថិតិ",
    "cancel": "បង្ហាញ",
    "confirm": "រក្សាទុក",
    "send_application": "Send Application",
  },
  tl: {
    "sign_in": "MAGPASOK",
    "sign_up": "MAGPAREHISTRO",
    "home": "Tahanan",
    "wallet": "Wallet",
    "hub_kami": "Hub Kami",
    "promotion": "Promosyon",
    "p2p": "P2P",
    "language": "Wika",
    "deposit": "Deposito",
    "withdraw": "Mag-withdraw",
    "game_hit": "Piling Laro",
    "slot": "Slot",
    "casino": "Kasino",
    "sportsbook": "Palaro",
    "fishing": "Pangisda",
    "arcade": "Arcade",
    "cockfighting": "Sabong",
    "togel": "Togel",
    "play": "MAGLARO",
    "profile": "Profile",
    "history": "Kasaysayan",
    "cashback": "Cashback",
    "earn_money": "Kumita",
    "credit_point": "Libre Credit/Points",
    "coupon": "Kupon",
    "randombox": "Random Box",
    "wheel": "Gulong",
    "check_in": "Check In",
    "ranking": "Ranggo",
    "contact_us": "Makipag-ugnayan sa Amin",
    "switch_language": "Magpalit ng Wika",
    "manual": "Manual",
    "download_guild": "I-download ang Guild",
    "announcement": "🎉 Anunsyo: DEMO Gacor Gaming Kumuha ng Espesyal na Bonus & Promosyon",
    "free_spins": "💰 Manalo ng Malaki sa 100 Libre Spins - Deposito Lamang $100",
    "promotion_bonus": "🎁 Espesyal na Promosyon: 50% Bonus sa Lahat ng Larong Araw-araw",
    "welcome_bonus": "⭐ Sumali Ngayon at Makatanggap ng 100 Libreng Puntos bilang Welcome Bonus",
    "search_games": "Maghanap ng mga laro...",
    "username": "Pangalan ng gumagamit",
    "password": "Password",
    "confirm_password": "Kumpirmahin ang Password",
    "email": "Email",
    "phone": "Numero ng Telepono",
    "login": "Magpasok",
    "register": "Magparehistro",
    "forgot_password": "Nakalimutan ang Password",
    "logout": "Mag-logout",
    "have_account": "Mayroon na ba kayong account?",
    "password_mismatch": "Hindi tumutugma ang password",
    "phone_number": "Numero ng Telepono",
    "please_enter_phone": "Mangyaring ipasok ang iyong numero ng telepono",
    "please_enter_password": "Mangyaring ipasok ang iyong password",
    "remember_me": "Alalahanin ako",
    "forgot_password_q": "Nakalimutan ang Password??",
    "found_problem": "Nakahanap ng problema",
    "contact_customer_service": "Makipag-ugnayan sa Customer Service",
    "play": "MAGLARO",
    "credit_balance": "Credit Balance",
    "wallet": "Wallet",
    "promotion": "Promosyon",
    "turnover": "Turnover",
    "credit_free": "Libreng Credit",
    "point_free": "Libreng Puntos",
    "coupon": "Kupon",
    "random_box": "Random Box",
    "wheel": "Gulong",
    "exchange": "Palitan",
    "tournament": "Laban",
    "deposit_withdraw": "Deposito - I-withdraw",
    "deposit": "Deposito",
    "withdraw": "Mag-withdraw",
    "deposit_auto": "Awtomatikong Deposito",
    "deposit_decimal": "Decimal Deposito",
    "truemoney": "Truemoney",
    "deposit_confirm_slip": "Slip ng Pagsasaad ng Deposito",
    "true_gift": "Tunay na Handog",
    "deposit_confirm": "Pagsasaad ng Deposito",
    "line_bot_notification": "Notipikasyon ng Line Bot",
    "normal_withdraw": "Normal na Pag-withdraw",
    "max_withdraw": "Pinakamataas na Pag-withdraw",
    "withdraw_to_account": "I-withdraw ang iyong pera sa account",
    "bio": "BIO",
    "have_questions_readmore": "May karagdagang mga tanong? Basahin Pa",
    "hub_kami": "Hub Kami",
    "contact_us": "Makipag-ugnayan sa Amin",
    "live_chat_support": "Suportang Live Chat",
    "available_24_7": "Available 24/7",
    "email": "Email",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "Pangunahing Menu",
    "income_menu": "Menu ng Kita",
    "event_menu": "Menu ng Kaganapan",
    "more_menu": "Higit pang Menu",
    "logout": "Mag-logout",
    "user_id": "User ID",
    "balance": "Balanse",
    "point": "Puntos",
    "choose_your_bank": "Pumili ng Iyong Bank",
    "enter_bank_number": "Ipasok ang Iyong Numero ng Bank",
    "name_lastname": "pangalan - apelyido",
    "how_do_know_us": "Paano mo kami nakilala?",
    "choose_receive_bonus": "Piliin kung makatanggap ng bonus o hindi",
    "receive": "Makatanggap",
    "not_receive": "Hindi makatanggap",
    "sign_up_modal": "MAGPAREHISTRO",
    "enter_banknumber": "Ipasok ang Iyong Numero ng Bank",
    "personal_info": "Impormasyon ng Personal",
    "bank_info": "Impormasyon ng Bank Account",
    "bank_type": "Likhang Bank",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "Pangalan ng Bank Account",
    "account_number": "Numero ng Account",
    "banking": "Pangmula",
    "choose_deposit_method": "Pumili ng Paraan ng Deposito",
    "choose_payment_method": "Pumili ng iyong preferred na paraan ng pagbabayad",
    "qris": "QRIS",
    "bank_transfer": "Bank Transfer",
    "e_wallet": "E-Wallet",
    "pulsa": "Pulsa",
    "scan_qr_instant": "I-scan ang QR code para sa instant na deposito",
    "transfer_bank_for_deposit": "Bank transfer para sa secure na deposito",
    "dana_ovo_gopay": "DANA, OVO, GoPay, at iba pa",
    "deposit_via_pulsa": "Deposito sa pamamagitan ng prepaid pulsa",
    "instant": "Instant",
    "30_60_seconds": "30 - 60Araw",
    "select_qris_provider": "Pumili ng QRIS Provider",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "Online",
    "deposit_amount": "Halaga ng Deposito",
    "enter_deposit_amount": "Magpasok ng halaga ng deposito",
    "idr": "IDR",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "choose_promo": "Pumili ng Promo (Opsyonal)",
    "choose_promo_optional": "Pumili ng promo (opsyonal)",
    "payment_summary": "Buod ng Pagbabayad",
    "total_deposit": "Halaga ng Deposito:",
    "promo_discount": "Halaga ng Pagbabayad:",
    "total": "Kabuuan:",
    "confirm_deposit": "Kumpirmahin ang Deposito",
    "rp_0": "Rp 0",
    "select_your_account": "Pumili ng Iyong Account",
    "destination_account": "Destination Account",
    "select_destination": "Pumili ng destination account",
    "bank_account_info": "Impormasyon ng Account",
    "bank_name": "Pangalan ng Bank",
    "account_holder": "Nagmamay-ari ng Account",
    "recipient_number": "Numero ng Tumanggap",
    "upload_receipt": "Resibo ng Pagbabayad (Opsyonal)",
    "click_upload_receipt": "I-click upang mag-upload ng resibo ng pagbabayad",
    "additional_notes": "Karagdagang Mga Tala (opsyonal)",
    "enter_notes": "No.Ref / Pangalan ng Nagpadala",
    "select_wallet": "Pumili ng E-Wallet",
    "select_ewallet_number": "Pumili ng e-wallet number",
    "select_admin_number": "Pumili ng Admin Number",
    "recipient_phone": "SN / Numero ng Tumanggap",
    "enter_recipient_phone": "Magpasok ng SN number",
    "withdrawal": "Pag-withdraw",
    "withdrawal_history": "Kasaysayan ng Pag-withdraw",
    "coming_soon": "Paparating Na",
    "profile_settings": "Mga Setting ng Profile",
    "profile_information": "Impormasyon ng Profile",
    "account_details": "Mga Detalye ng Account",
    "account_tier": "Antas ng Account",
    "change_password": "Baguhin ang Password",
    "current_password": "Kasalukuyang Password",
    "enter_current_password": "Ipasok ang iyong kasalukuyang password",
    "new_password": "Bagong Password",
    "enter_new_password": "Ipasok ang iyong bagong password",
    "update_password_instruction": "I-update ang iyong password",
    "banking_accounts": "Mga Akong Pang-bank",
    "add_bank": "Magdagdag ng Bank",
    "active": "Aktibo",
    "security": "Seguridad",
    "referral_program": "Program ng Referral",
    "earn_bonus_from_referrals": "Kumita ng bonus mula sa iyong mga referral",
    "referral_app_info": "Referral program application na may structured form",
    "first_name": "Pangalang",
    "enter_first_name": "Ipasok ang iyong pangalan",
    "enter_email": "Ipasok ang iyong email address",
    "enter_phone_number": "Ipasok ang iyong numero ng telepono",
    "address": "Tirahan",
    "enter_address": "Ipasok ang iyong buong address",
    "bank_ewallet": "Bank/E-Wallet",
    "choose_bank_ewallet": "Pumili ng Iyong Bank/E-Wallet",
    "identity_file": "Documento ng Pagkakakilanlan (ID/Lisensya/Pasaporte)",
    "click_upload_identity": "I-click o ikyot ang iyong dokumento dito",
    "file_format_limit": "Format: JPG, PNG - Pinakamalaki 10MB",
    "submit_application": "Ipadala ang Aplikasyon",
    "referral_tree": "Puno ng Referral",
    "total_referral": "Kabuuang Referral",
    "no_referrals_yet": "Walang referral pa",
    "invite_people_to_join": "Anyayahan ang mga tao na sumali at makakuha ng bonus",
    "referral_structure_display": "Ang iyong istruktura ng referral ay ipapakita dito",
    "data_turnover": "Lihim ng Data",
    "view_performance": "Subaybayan ang iyong performance sa paglalaro",
    "filter_data": "I-filter ang Data",
    "start_date": "Petsa ng Simula",
    "end_date": "Petsa ng Pagtatapos",
    "category": "Kategorya",
    "provider": "Provider",
    "all_categories": "Lahat ng Kategorya",
    "all_providers": "Lahat ng Provider",
    "search_data": "Maghanap ng Data",
    "search_results": "Mga Resulta ng Paghahanap",
    "results": "mga resulta",
    "no_data_yet": "Walang data ng turnover pa",
    "adjust_filter_to_see_data": "I-adjust ang filter o petsa upang makita ang iyong data ng turnover",
    "statistics": "Mga Istatistika",
    "cancel": "Magbawi",
    "confirm": "I-save",
    "send_application": "Send Application",
  },
  ko: {
    "sign_in": "로그인",
    "sign_up": "가입",
    "home": "홈",
    "wallet": "지갑",
    "hub_kami": "Hub Kami",
    "promotion": "프로모션",
    "p2p": "P2P",
    "language": "언어",
    "deposit": "입금",
    "withdraw": "출금",
    "game_hit": "인기게임",
    "slot": "슬롯",
    "casino": "카지노",
    "sportsbook": "스포츠",
    "fishing": "낚시",
    "arcade": "아케이드",
    "cockfighting": "닭싸움",
    "togel": "토겔",
    "play": "플레이",
    "profile": "프로필",
    "history": "히스토리",
    "cashback": "캐시백",
    "earn_money": "돈 벌기",
    "credit_point": "무료 크레딧/포인트",
    "coupon": "쿠폰",
    "randombox": "랜덤박스",
    "wheel": "휠",
    "check_in": "체크인",
    "ranking": "랭킹",
    "contact_us": "문의하기",
    "switch_language": "언어 전환",
    "manual": "설명서",
    "download_guild": "길드 다운로드",
    "announcement": "🎉 공지: DEMO Gacor Gaming 특별 보너스 및 프로모션",
    "free_spins": "💰 100 프리스핀으로 큰 상금 획득 - $100만 입금",
    "promotion_bonus": "🎁 특별 프로모션: 모든 게임 매일 50% 보너스",
    "welcome_bonus": "⭐ 지금 가입하고 웰컴 보너스로 100 무료 포인트 받기",
    "search_games": "게임 검색...",
    "username": "사용자명",
    "password": "비밀번호",
    "confirm_password": "비밀번호 확인",
    "email": "이메일",
    "phone": "전화번호",
    "login": "로그인",
    "register": "가입",
    "forgot_password": "비밀번호 잊음",
    "logout": "로그아웃",
    "have_account": "이미 계정이 있으신가요?",
    "password_mismatch": "비밀번호가 일치하지 않습니다",
    "phone_number": "전화번호",
    "please_enter_phone": "전화번호를 입력하세요",
    "please_enter_password": "비밀번호를 입력하세요",
    "remember_me": "날 기억해",
    "forgot_password_q": "비밀번호를 잊으셨나요??",
    "found_problem": "문제를 발견했습니다",
    "contact_customer_service": "고객 서비스에 문의",
    "play": "플레이",
    "credit_balance": "크레딧 잔액",
    "wallet": "지갑",
    "promotion": "프로모션",
    "turnover": "매출액",
    "credit_free": "무료 크레딧",
    "point_free": "무료 포인트",
    "coupon": "쿠폰",
    "random_box": "랜덤박스",
    "wheel": "휠",
    "exchange": "교환",
    "tournament": "토너먼트",
    "deposit_withdraw": "입금・출금",
    "deposit": "입금",
    "withdraw": "출금",
    "deposit_auto": "자동 입금",
    "deposit_decimal": "소수 입금",
    "truemoney": "트루머니",
    "deposit_confirm_slip": "입금 확인 증명서",
    "true_gift": "진정한 선물",
    "deposit_confirm": "입금 확인",
    "line_bot_notification": "Line 봇 알림",
    "normal_withdraw": "일반 출금",
    "max_withdraw": "최대 출금",
    "withdraw_to_account": "계좌로 돈을 인출",
    "bio": "바이오",
    "have_questions_readmore": "추가 질문이 있으신가요? 자세히 읽기",
    "hub_kami": "Hub Kami",
    "contact_us": "문의하기",
    "live_chat_support": "라이브 채팅 지원",
    "available_24_7": "24/7 이용 가능",
    "email": "이메일",
    "telegram": "Telegram",
    "whatsapp": "Whatsapp",
    "main_menu": "주 메뉴",
    "income_menu": "소득 메뉴",
    "event_menu": "이벤트 메뉴",
    "more_menu": "더 많은 메뉴",
    "logout": "로그아웃",
    "user_id": "사용자 ID",
    "balance": "잔액",
    "point": "포인트",
    "choose_your_bank": "은행 선택",
    "enter_bank_number": "은행 번호 입력",
    "name_lastname": "이름 - 성",
    "how_do_know_us": "어디서 우리를 알게 되었나요?",
    "choose_receive_bonus": "보너스 받기 여부를 선택하세요",
    "receive": "수령",
    "not_receive": "수령하지 않음",
    "sign_up_modal": "가입",
    "enter_banknumber": "은행 번호를 입력하세요",
    "personal_info": "개인 정보",
    "bank_info": "은행 계좌 정보",
    "bank_type": "은행 유형",
    "bca": "BCA",
    "bni": "BNI",
    "bri": "BRI",
    "mandiri": "Mandiri",
    "bank_account_name": "은행 계좌명",
    "account_number": "계좌 번호",
    "banking": "뱅킹",
    "choose_deposit_method": "입금 방법 선택",
    "choose_payment_method": "원하는 결제 방법을 선택하세요",
    "qris": "QRIS",
    "bank_transfer": "은행 이체",
    "e_wallet": "전자 지갑",
    "pulsa": "Pulsa",
    "scan_qr_instant": "QR 코드를 스캔하여 즉시 입금",
    "transfer_bank_for_deposit": "안전한 입금을 위한 은행 이체",
    "dana_ovo_gopay": "DANA, OVO, GoPay 등",
    "deposit_via_pulsa": "선불 Pulsa를 통한 입금",
    "instant": "즉시",
    "30_60_seconds": "30 - 60일",
    "select_qris_provider": "QRIS 공급자 선택",
    "kitapay": "Kitapay",
    "garuda_pay": "Garuda Pay",
    "mvp_pay": "MVP Pay",
    "online": "온라인",
    "deposit_amount": "입금액",
    "enter_deposit_amount": "입금액을 입력하세요",
    "idr": "IDR",
    "minimum": "최소",
    "maximum": "최대",
    "choose_promo": "프로모션 선택 (선택 사항)",
    "choose_promo_optional": "프로모션 선택 (선택 사항)",
    "payment_summary": "결제 요약",
    "total_deposit": "입금액:",
    "promo_discount": "결제액:",
    "total": "총액:",
    "confirm_deposit": "입금 확인",
    "rp_0": "Rp 0",
    "select_your_account": "계정 선택",
    "destination_account": "목표 계정",
    "select_destination": "목표 계정 선택",
    "bank_account_info": "계정 정보",
    "bank_name": "은행명",
    "account_holder": "계좌 소유자",
    "recipient_number": "수신자 번호",
    "upload_receipt": "결제 영수증 (선택 사항)",
    "click_upload_receipt": "클릭하여 결제 영수증 업로드",
    "additional_notes": "추가 메모 (선택 사항)",
    "enter_notes": "No.Ref / 발신자 이름",
    "select_wallet": "전자 지갑 선택",
    "select_ewallet_number": "전자 지갑 번호 선택",
    "select_admin_number": "관리자 번호 선택",
    "recipient_phone": "SN / 수신자 번호",
    "enter_recipient_phone": "SN 번호 입력",
    "withdrawal": "인출",
    "withdrawal_history": "인출 내역",
    "coming_soon": "곧 출시",
    "profile_settings": "프로필 설정",
    "profile_information": "프로필 정보",
    "account_details": "계정 세부 정보",
    "account_tier": "계정 등급",
    "change_password": "비밀번호 변경",
    "current_password": "현재 비밀번호",
    "enter_current_password": "현재 비밀번호를 입력하세요",
    "new_password": "새 비밀번호",
    "enter_new_password": "새 비밀번호를 입력하세요",
    "update_password_instruction": "비밀번호 업데이트",
    "banking_accounts": "은행 계좌",
    "add_bank": "은행 추가",
    "active": "활성",
    "security": "보안",
    "referral_program": "추천 프로그램",
    "earn_bonus_from_referrals": "추천으로 보너스 획득",
    "referral_app_info": "구조화된 양식이 있는 추천 프로그램 애플리케이션",
    "first_name": "이름",
    "enter_first_name": "이름을 입력하세요",
    "enter_email": "이메일 주소를 입력하세요",
    "enter_phone_number": "전화번호를 입력하세요",
    "address": "주소",
    "enter_address": "전체 주소를 입력하세요",
    "bank_ewallet": "은행/전자지갑",
    "choose_bank_ewallet": "은행/전자지갑 선택",
    "identity_file": "신원 파일 (ID/운전면허증/여권)",
    "click_upload_identity": "여기를 클릭하거나 신원 파일을 드래그",
    "file_format_limit": "형식: JPG, PNG - 최대 10MB",
    "submit_application": "신청서 제출",
    "referral_tree": "추천 트리",
    "total_referral": "총 추천",
    "no_referrals_yet": "아직 추천이 없습니다",
    "invite_people_to_join": "사람들을 초대하고 보너스를 받으세요",
    "referral_structure_display": "추천 구조가 여기에 표시됩니다",
    "data_turnover": "데이터 회전율",
    "view_performance": "필터를 사용하여 게임 성능을 모니터링",
    "filter_data": "데이터 필터",
    "start_date": "시작 날짜",
    "end_date": "종료 날짜",
    "category": "카테고리",
    "provider": "제공자",
    "all_categories": "모든 카테고리",
    "all_providers": "모든 제공자",
    "search_data": "데이터 검색",
    "search_results": "검색 결과",
    "results": "결과",
    "no_data_yet": "아직 회전율 데이터가 없습니다",
    "adjust_filter_to_see_data": "필터 또는 날짜를 조정하여 회전율 데이터 보기",
    "statistics": "통계",
    "cancel": "취소",
    "confirm": "저장",
    "send_application": "Send Application",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("id");

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
